DROP DATABASE IF EXISTS stockmarketdb;

CREATE DATABASE IF NOT EXISTS stockmarketdb;

USE stockmarketdb;

/*Dropping tables if already created*/
DROP TABLE IF EXISTS RegisterMaster;
DROP TABLE IF EXISTS TransactionMaster;
DROP TABLE IF EXISTS Sector;
DROP TABLE IF EXISTS Company;


/*Creating tables*/
CREATE TABLE IF NOT EXISTS RegisterMaster
(
   
    RID BIGINT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Cpassword VARCHAR(255) NOT NULL,
    ClientID VARCHAR(255) NOT NULL,
    PRIMARY KEY(RID)
    
);

CREATE TABLE IF NOT EXISTS TransactionMaster
(
    TID BIGINT NOT NULL AUTO_INCREMENT,
    SID BIGINT,
    CID BIGINT,
    RID BIGINT,
    Nshares BIGINT,
    Rate BIGINT,
    NetAmt BIGINT,
    FOREIGN KEY (SID) REFERENCES Sector(SID),
    FOREIGN KEY (CID) REFERENCES Company(CID),
    FOREIGN KEY (RID) REFERENCES RegisterMaster(RID) ON DELETE CASCADE,
    PRIMARY KEY(TID)
    
);

CREATE TABLE IF NOT EXISTS Sector(
    SID BIGINT NOT NULL AUTO_INCREMENT,
    Sname VARCHAR(255) NOT NULL,
    PRIMARY KEY(SID)
);

CREATE TABLE IF NOT EXISTS Company(
    CID BIGINT NOT NULL AUTO_INCREMENT,
    SID BIGINT,
    Cname VARCHAR(255) NOT NULL,
    FOREIGN KEY (SID) REFERENCES Sector(SID) ON DELETE CASCADE,
    PRIMARY KEY(CID)
);